# Netlify configuration file

# Build settings
[build]
  publish = "dist"
  command = "npm run build"

# Redirects for API endpoints
[[redirects]]
  from = "/api/*"
  to = "https://services.dzaleka.com/api/:splat"
  status = 200
  force = true  # Ensures the redirect works even if the route exists


# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

# Environment variables
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/updates"
  to = "/updates/1"
  status = 302